### ISSUE TITLE
swagger file is incorrect

### ISSUE THREAD

**Issue by marsom** [SwissSign-AG/RaApi#1]
I generated a java client with the java http client (java17, without okhttp3) and i found some stuff wich does not work:

/v2/jwt/{userName}
- the 200 response content type is defined as application/json but it is text/plain
- https://github.com/SwissSign-AG/RaApi#generate-a-user-jwt-given-an-account-and-api-key
  -  if you do a curl you see that the response is text/plain

/v2/issue/csr/{productReference}
- the request content type is defined as application/json but it is text/plain
- the example in https://github.com/SwissSign-AG/RaApi#issue-a-certificate-using-a-csr-for-the-selected-certificate-product correctly set it to text/plain

wihout this modification the generated plain java17 with the java http client does not work.

best regards.

**Comment by opensource-swisssign** [comment]
Dear @marsom 

Thank you very much for reporting this issue.

Your issue #1 is now considered resolved (https://github.com/SwissSign-AG/RaApi/commit/801fad34ecef9672fdd913b008feb5d028b14236), therefore we’re closing the ticket.

If there is anything else we can support you with, please do not hesitate to contact us.

Have a good day.

Your SwissSign team
